from __future__ import annotations

from pathlib import Path
from typing import Optional

def dedup_ndjson(input: Path, output: Path, is_edges: bool, domain: Optional[str] = None) -> None: ...
def graph_uuid(domain: Optional[str], row_json: str) -> str: ...
def namespace_uuid(domain: str, values: list[str]) -> str: ...
