from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

def build_fullmap_db(
    output: Path, classes: list[Path], synonyms: list[Path], source_version: str, threads: Optional[int] = None, write_batch_size: int = 50_000
) -> None: ...
def dedup_ndjson(input: Path, output: Path, is_edges: bool, domain: Optional[str] = None) -> None: ...
def fullmap_source_version() -> str: ...
def hydrate_categories(db: Path) -> list[str]: ...
def hydrate_curies(db: Path, curie_ids: list[int]) -> list[dict[str, Any]]: ...
def hydrate_prefixes(db: Path) -> list[str]: ...
def hydrate_sources(db: Path) -> list[str]: ...
def lookup_fullmap_terms(db: Path, terms: list[str], threads: Optional[int] = None, return_format: str = "rows") -> list[dict[str, Any]]: ...
def namespace_uuid(domain: str, values: list[str]) -> str: ...
