repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        args: [./flake.nix]
        language: system
        types: [nix]
        pass_filenames: false