site_name: Tablassert
theme: readthedocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Docker: docker.md
  - Fullmap: fullmap.md
  - CLI Reference: cli.md
  - Tutorial: tutorial.md
  - Use Case Gallery: examples.md
  - Configuration:
    - Graph Config: configuration/graph.md
    - Table Config: configuration/table.md
    - Advanced Example: configuration/advanced-example.md
  - API Reference:
    - Entity Resolution: api/fullmap.md
    - Batch Resolution: api/lib.md
    - Quality Control: api/qc.md
    - Utilities: api/utils.md
  - Changelog: changelog.md
