[project]
name = "tablassert"
version = "7.2.1"
description = "Tablassert is a highly performant declarative knowledge graph backend designed to extract knowledge assertions from tabular data while exporting NCATS Translator-compliant Knowledge Graph Exchange (KGX) NDJSON."
authors = [
    { name = "Skye Lane Goetz", email = "sgoetz@isbscience.org" }
]
keywords = [
    "knowledge graph",
    "bioinformatics",
    "entity resolution",
    "ner",
    "ncats translator",
    "kgx",
    "yaml configuration",
    "table mining",
    "declarative pipeline",
    "data quality control",
    "tablassert",
]
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Framework :: Pydantic",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.5.0",
    "fastexcel>=0.19.0",
    "lazy-loader>=0.5",
    "loguru>=0.7.3",
    "onnxruntime>=1.24.4",
    "optimum-onnx>=0.1.0",
    "orjson>=3.11.7",
    "playwright>=1.58.0",
    "polars>=1.39.0",
    "polars-hash>=0.5.6",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.5",
    "pyexcel>=0.7.4",
    "pyyaml>=6.0.3",
    "rapidfuzz>=3.14.3",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.3.0",
    "sqlite-utils>=3.39",
    "typer>=0.24.1",
    "xxhash>=3.6.0",
]

[project.urls]
Homepage = "https://github.com/SkyeAv/Tablassert"
Source = "https://github.com/SkyeAv/Tablassert"
Documentation = "https://skyeav.github.io/Tablassert/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["./src/tablassert"]

[project.scripts]
tablassert = "tablassert.cli:CLI"

[project.optional-dependencies]
rtcompat = [
    "polars[rtcompat]>=1.39.0",
]
rt = [
    "tablassert[rtcompat]",
]

[dependency-groups]
dev = [
    "grayskull>=3.1.0",
    "mkdocs>=1.6.1",
    "pre-commit>=4.5.1",
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "ruff>=0.15.6",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
